### ISSUE TITLE
Rename default branch to `main`

### ISSUE THREAD

**Issue by pzelnip** [yyjtech/code-of-conduct#8]
Noticed that the default branch on this repository is still `master`.  Ideally [following trends in industry in the interest of being more culturally sensitive](https://www.theserverside.com/feature/Why-GitHub-renamed-its-master-branch-to-main), a different branch name should be used.

**Comment by brettgoss** [comment]
Hey @pzelnip, thanks for raising this! We noticed this recently too, and updated the default branches of all of the YYJ Tech repos. Should be resolved now!
